### ISSUE TITLE
请教一下，在centos docker 无法启动

### ISSUE THREAD

**Issue by lonelyxmas** [NewLifeX/Stardust#12]
nhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'System.Data.SQLite.SQLiteFactory' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'SQLite.Interop.dll' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.4/SQLite.Interop.dll.so: cannot open shared object file: No such file or directory
/app/SQLite.Interop.dll.so: cannot open shared object file: No such file or directory

**Comment by nnhy** [comment]
这是因为缺少SQLite运行时，在虚拟机运行的时候，它能够自动联网下载。
你可以在项目里面通过nuget引用sqlite.data
