### ISSUE TITLE
QueueService发布消息拼写错误：）

### ISSUE THREAD

**Issue by Xusp** [NewLifeX/Stardust#2]
/// <summary>主动式消息服务</summary>
    /// <typeparam name="T">数据类型</typeparam>
    public interface IQueueService<T>
    {
        /// <summary>发布消息</summary>
        /// <param name="topic">主题</param>
        /// <param name="value">消息</param>
        /// <returns></returns>
        Int32 Public(String topic, T value);

**Comment by nnhy** [comment]
已修正 Publish
