### ISSUE TITLE
stardust是否有docker部署的方案？

### ISSUE THREAD

**Issue by zkaitanx** [NewLifeX/Stardust#3]
我们公司的不同服务部署在腾讯云的容器集群上，想尝试使用stardust做链路监控。初步看md似乎stardust需要部署agent到应用服务器上做守护进程监控上报数据，请问是否有部署到docker集群的方案？

**Comment by nnhy** [comment]
如果想用星尘做链路监控，不需要StarAgent，只需要应用引入NewLife.Stardust包即可。
该包会采集数据，定期上报给监控中心。

StarAgent只用于管理节点，以及做远程发布。

**Comment by zkaitanx** [comment]
明白  我们用这个思路尝试下 谢谢
