### ISSUE TITLE
关于StarAgent停止服务后，被拉起服务进程没有停止。

### ISSUE THREAD

**Issue by flyeagle0032** [NewLifeX/Stardust#5]
关于StarAgent停止服务后，被拉起服务进程没有停止。这个你说是BUG他又不算BUG，最后觉得应该是个机制问题。有的应用，可能要随着StarAgent的停止而停止，有的确实不跟随StarAgent的停止而停卡，所以想可否增加一个配置，即是否自动停止AutoStop，如果AutoStop=true即随着StarAgent的启停而启停，false则反之。谢谢大佬。

**Comment by nnhy** [comment]
/// <summary>是否自动停止。随着宿主的退出，同时停止该应用进程</summary>
        [XmlAttribute]
        public Boolean AutoStop { get; set; }
