### ISSUE TITLE
StarAgent守护服务，增加配置AutoStop，某些应用需要跟随StarAgent退出而退出

### ISSUE THREAD

**Issue by nnhy** [NewLifeX/Stardust#61]
StarAgent守护服务，增加配置AutoStop，某些应用需要跟随StarAgent退出而退出

@dingchun

**Comment by qcjxberin** [comment]
已增加

**Comment by nnhy** [comment]
#61 StarAgent守护服务，增加配置AutoStop，某些应用需要跟随StarAgent退出而退出 · NewLifeX/Stardust@fce0e23
https://github.com/NewLifeX/Stardust/commit/fce0e23788f7ee5da7b4ad69d6416d28bec51dd9
