### ISSUE TITLE
“参数路径补全”导致的致命错误

### ISSUE THREAD

**Issue by nnhy** [NewLifeX/Stardust#70]
以下代码发生致命错误。https://star.newlifex.com/trace?id=ac1007eb172486341696902a0e55a2
参数 urls=http://*:8090 被错误处理为 /root/oqe/web/urls=http:/*:8090
系统 Ubuntu 22.04
注：命令行中的参数非常灵活，可能是各种字符串，在不确定它是路径之前，贸然补全路径可能会引发更多问题
@AvenSun 

`
// 参数中有路径的补全
if (args[i].Contains('/') || args[i].Contains('\\'))
{
    //不是绝对路径再补
    if (!Path.IsPathRooted(args[i]))
    {
        //工作目录不为空时
        if (!WorkingDirectory.IsNullOrEmpty())
        {
            args[i] = WorkingDirectory.CombinePath(args[i]).GetFullPath();
        }
        else
        {
            args[i] = args[i].GetFullPath();
        }                        
    }
    WriteLog("参数路径补全 {0}", args[i]);
}
`

**Comment by AvenSun** [comment]
@nnhy 

抱歉考虑不周！

**Comment by nnhy** [comment]
没关系！
这个地方早期我也犯过错误，后来才搞明白，这里会出现各种可能。因此我们代码不再做预处理
